language: c
install : make get-deps 
compiler : - gcc
matrix:
  include:
	- os: linux
	      addons:
	        apt:
	          sources:
	            - ubuntu-toolchain-r-test
	          packages:
	            - g++-5
	      env:
	         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
 
